### PR TITLE
Normalize logical id of alias part in Lambda roles

### LINKED ISSUE #68: Error when creating aliases with "-" in the name
I've tried to deploy a new alias called "my-test" using `sls deploy --alias my-test`. Unfortunately this fails with an exception:

```bash
  The CloudFormation template is invalid: Template format error: Resource name IamRoleLambdaExecutionmy-test is non alphanumeric.
```

The alias stack is still created and not cleaned up properly. I suggest to simply use camel casing when appending the alias name to CloudFormation resources. That would fix this while still allowing non alphanumeric characters in the alias name itself.

### PR DESCRIPTION
**Pull request by HyperBrain**
Fixes #68 

Aliases can now include characters matching `[a-zA-Z0-9\-+_]+`.
To generate a valid role logical id for the alias, the alias name is normalized by using the following table:
```
- => Dash
+ => Plus
_ => Uscore
```
This should work as it is highly unlikely that someone uses one of the replacement strings in real alias names.

### CODE REVIEW

**Comment by HyperBrain** [comment]
Locally ESLint as well as the testsuite passes. Will have to check why Travis fails.

**Comment by HyperBrain** [comment]
Had to upgrade eslint and the testsuite. However unit tests for the normalized roles are yet missing.

**Comment by HyperBrain** [comment]
@mbruning24 @arabold - Could you do a test with `HyperBrain/serverless-aws-alias#normalize-role-name` and check if aliases that include dashes work now?

**Comment by mbruning24** [comment]
@HyperBrain sorry it's been a hectic couple weeks. I tested this out. Error looks great BTW!

However, I found a HUGE bummer. API Gateway doesn't allow hyphens in the stage name! What a joke! I mean, come one AWS, it's a URL for crying out loud... The regex for that is /a-zA-Z0-9_/, so underscores are allowed by APIG, but ironically not by the regex! Maybe just switch that bad boy from hyphen to underscore and you'll have really done all you can. Hopefully AWS lets hyphens in stage names sometime in the future.

**Comment by HyperBrain** [comment]
@mbruning24 That's indeed ridiculous. I'll add a light normalization to the stage name creation which only will transform the hyphen as you proposed.
However I have to add that to the docs, because having both aliases `my-alias` and `my_alias` would lead to a crash then. Maybe we should even emit a warning in case `-` or `_` are used in an alias.

The hyphen issue on AWS side would imo justify to open a issue/case on their side. Stage names should comply with the official URL rules.

**Comment by mbruning24** [comment]
@HyperBrain I've opened a support case with AWS in our company account. For now, I'd be happy with just underscore though, if you wouldn't mind changing that.

**Comment by HyperBrain** [comment]
No problem. Will do.

Mark Bruning <notifications@github.com> schrieb am Fr., 3. Nov. 2017, 8:05
nachm.:

**Comment by HyperBrain** [comment]
@mbruning24 Sorry for the delay. Now, for stage names the hyphens are replaced by underscores.

Did you get any valuable feedback from AWS yet?

**Pull request merged**
